[workspace]
members = [
    "basilisk/compiler/basilisk_compile_python_stdlib",
    "basilisk/compiler/basilisk_generate",
    "basilisk/compiler/basilisk_vm_value_derive",
]
exclude = ["examples"]
edition = "2018"
